### ISSUE TITLE
Will it be possible to update it to 2.0

### ISSUE THREAD

**Issue by popovae** [zenobase/geocluster-facet#21]
Hi,

Any plans to update this plugin to work under ES 2.0?

Thank you!

**Comment by ejain** [comment]
Not sure yet: ES2 no longer supports facets, so this plugin will have to rewritten as an "aggregation". Moreover, ES now ships with a "geohash" aggregation that can do much of the same.

**Comment by popovae** [comment]
Hi Eric,

To be honest I didn't find any information about support of facets in ES2...according to the docs Facets were deprecated long ago, but geocluster-facet was working...

"geohash" aggregation - it is shiped till ES 1.2 but to be honest - useless and it uses another algorithms of calculation...as far as I can understand...

Eric, can you please contact me via email or skype, maybe we can find the way to rework this plugin?)
popov.andrey@me.com  popov_ae

**Comment by ejain** [comment]
Facets have been deprecated for a while now, and were completely removed in ES2. I have another plugin (zenobase/decimal-histogram-facet) that I need to rewrite first, which should give me an idea how much effort is required to rewrite this one...

**Comment by popovae** [comment]
Hi Eric,

Any updates on this? Did you manage to figure out how to rewrite your "other plugin"?)

**Comment by ejain** [comment]
Not yet, but am planning to work on this next month, as we need to migrate to ES2, too.

**Comment by popovae** [comment]
Hi Ejain,

I tried to find someone to accomplish this...but still no luck at all... Any chance you at least had a look at the way to modify this plugin, or you had no time?)) You are the only hope left to migrate finally to new ES)))

**Comment by sandervanhooft** [comment]
@ejain I see little activity here... Do you perhaps have a pointer to how to replicate this plugin's behaviour in ES 2.4?

I get the impression that the geohash aggregation function will not offer the same results.

**Comment by ejain** [comment]
The idea is to use the geohash aggregation to pre-aggregate the data into a few hundred buckets, and then run the clustering algorithm on that. The result is not exactly the same, but this approach is much more scalable.

**Comment by sandervanhooft** [comment]
@ejain That sounds workable. Do you have some example of that?

**Comment by ejain** [comment]
Here's an even simpler solution that we ended up using: Use the built-in geohash aggregation with a slightly higher than necessary precision. Then calculate weighted centers for each parent geohash.
